



<div class="layout">
    <aside class="layout-aside">
        <button
            class="addCollection-btn"
            data-ajax="<?=buildUrl('add_collection')?>"
        >Create a new collection
        </button>





    </aside>


    <main>
        <div class="editCollectionOverlay overlay">
            <div class="editCollectionOverlay-container">
                <button class="closeEditCollectionOverlay">Close</button>
                <form id="edit-collection-form">
                    <div>
                        <label for="collectionTitle">Title:</label>
                        <input type="text" id="collectionTitle" name="collectionTitle" required>
                    </div>
                    <div>
                        <label for="collectionDescription">Description:</label>
                        <textarea id="collectionDescription" name="collectionDescription"></textarea>
                    </div>
                    <input type="hidden" id="idCollection" name="idCollection">
                    <button class="editCollectionBtn" type="submit">Edit Collection</button>
                </form>
            </div>
        </div>
        <div class="collectionsContainer">
            <?php foreach ($collections as $collection): ?>
                <div class="<?='collection-'.$collection['idCollection'] ?> collectionsContainer-collection">
                    <h3 id="collection-<?=$collection['idCollection'] ?>">
                        <?= $collection['title'] ?>
                    </h3>
                    <p><?= $collection['userText'] ?></p>


                    <?php if (count($collection['movies'])>0) : ?>
                        <p> Contain <?= count($collection['movies']); ?> movies</p>
                    <?php else: ?>
                        <p>No movie in that list</p>
                    <?php endif; ?>

                    <button data-idCollection="<?=$collection['idCollection'] ?>"
                            data-ajax="<?=buildUrl('delete_collection', ['idCollection' => $collection['idCollection']]);?>"
                            class="deleteCollection-btn" type="button">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                    <button data-idCollection="<?=$collection['idCollection'] ?>"
                            data-ajax="<?=buildUrl('edit_collection', ['idCollection' => $collection['idCollection']]);?>"
                            class="editCollection-btn" type="button">
                        <i class="fa-solid fa-pen"></i>
                    </button>
                    <a href="<?=buildUrl('view_collection', ['id' => $collection['idCollection']]);?>">
                        <button data-idCollection="<?=$collection['idCollection'] ?>" class="viewCollection-btn" type="button">
                            view collection
                        </button>
                    </a>

                </div>
            <?php endforeach; ?>

        </div>
    </main>
</div>

