<div class="allCollection">
    <?php if (isset($collections)): ?>
        <?php foreach ($collections as $collection): ?>

            <table class="<?='collection-'.$collection['idCollection'] ?>">
                <tr>
                    <th colspan="3">
                        <h3 id="collection-<?=$collection['idCollection'] ?>"><?= $collection['title'] ?></h3>
                        <button data-idCollection="<?=$collection['idCollection'] ?>"
                                data-ajax="<?=buildUrl('delete_collection', ['idCollection' => $collection['idCollection']]);?>"
                                class="deleteCollection-btn" type="button">
                            delete collection
                        </button>
                        <button data-idCollection="<?=$collection['idCollection'] ?>"
                                data-ajax="<?=buildUrl('edit_collection', ['idCollection' => $collection['idCollection']]);?>"
                                class="editCollection-btn" type="button">
                            edit collection
                        </button>
                        <a href="<?=buildUrl('view_collection', ['id' => $collection['idCollection']]);?>">
                            <button data-idCollection="<?=$collection['idCollection'] ?>" class="viewCollection-btn" type="button">
                                view collection
                            </button>
                        </a>

                    </th>
                </tr>
                <tr>
                    <th>Movie</th>
                    <th>Action</th>
                </tr>
                <?php if (isset($collection['movies']) && !empty($collection['movies'])): ?>
                    <?php foreach ($collection['movies'] as $movie): ?>
                        <tr class="<?='movie'.$movie['movieId'].'-'.'collection'.$collection['idCollection'] ?>">
                            <td>
                                <p id="<?="movie".$movie['movieId'] ?>"><?= $movie['title'] ?></p>
                            </td>
                            <td>
                                <button data-idCollection="<?=$collection['idCollection'] ?>"
                                        data-idMovie="<?=$movie['movieId'] ?>"
                                        data-ajax="<?=buildUrl('delete_movie_from_collection', ['idCollection' => $collection['idCollection'],'movieId' => $movie['movieId'] ]);?>"
                                        class="deleteMovieFromCollection-btn"
                                        type="button">
                                    remove from collection
                                </button>
                                <button data-idCollection="<?=$collection['idCollection'] ?>"
                                        data-idMovie="<?=$movie['movieId'] ?>"
                                        data-ajax="<?=buildUrl('edit_movie', ['movieId' => $movie['movieId']]);?>"
                                        class="editMovie-btn" type="button">
                                    edit movie
                                </button>
                                <a href="<?=buildUrl('view_movie', ['id' => $movie['movieId']]);?>">
                                    <button data-idCollection="<?=$collection['idCollection'] ?>"
                                            data-idMovie="<?=$movie['movieId'] ?>"
                                            class="viewMovie-btn" type="button">
                                        view movie
                                    </button>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                <?php else: ?>
                    <tr>
                        <td colspan="3">
                            <p>No movies in this collection</p>
                        </td>
                    </tr>
                <?php endif ?>
            </table>
        <?php endforeach ?>
    <?php endif; ?>
</div>


<!--TODO: display errors-->