<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>🎬 movietheque</title>
    <link rel="stylesheet" href="./styles/style.css">
    <script src="https://kit.fontawesome.com/0f005014e4.js" crossorigin="anonymous"></script>
    <?php if (isset ($script)):?>
        <?= $script;?>
    <?php endif;?>

</head>

<body>


<nav class="siteNav">
    <div class="siteNav-ToggleResponsive">MENU</div>
    <ul class="siteNav-list">
        <?php if (isConnected()): ?>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('home');?>" class="siteNav-list-item-link">
                    <i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>Home
                </a>
            </li>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('all_collection_from_user');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>Collections</a>
            </li>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('user_profile');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>Profile</a>
            </li>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('search_page');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>Search</a>
            </li>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('logout');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>Logout</a>
            </li>
        <?php endif; ?>
        <?php if (isConnected() && isAdmin()): ?>

        <?php endif; ?>


        <?php if (!isConnected()): ?>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('signup');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>sign up</a>
            </li>
            <li class="siteNav-list-item">
                <a href="<?=buildUrl('login');?>" class="siteNav-list-item-link"><i class="fa-solid fa-circle siteNav-list-item-link-icon"></i>login</a>
            </li>

        <?php endif; ?>

    </ul>
</nav>



<div class="background"></div>

    <?php if (isset($template)) {
        include '../templates/' . $template . '.phtml';
    } ?>
</body>
</html>