<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>🎬 Movie List 🎬</title>

    <script src="../public/script/js.js" defer></script>
</head>

<body>
    <nav class="siteNav">
        <a href="../controllers/home.php">home</a>
        <a href="../controllers/lists.php">all list</a>
        <a href="../controllers/signup.php">sign up</a>
        <a href="../controllers/login.php">login</a>
        <a href="../controllers/logout.php">logout</a>
    </nav>
    <?php if (isset($template)) {
        include '../templates/' . $template . '.phtml';
    } ?>
</body>
</html>