<div class="collection">
    <table class="<?='collection-'.$collection['idCollection'] ?>">
        <tr>
            <th colspan="4">
                <h3 id="collection-<?=$collection['idCollection'] ?>"><?= $collection['title'] ?></h3>
            </th>
            <td>
                <p><?= $collection['userId'] ?></p>
            </td>
            <td>
                <p><?= $collection['isFavorite'] ?></p>
            </td>
            <td>
                <p><?= $collection['createdAt'] ?></p>
            </td>
            <td>
                <p><?= $collection['userText'] ?></p>
            </td>
            <td>
                <button data-idCollection="<?=$collection['idCollection'] ?>"
                        data-ajax="<?=buildUrl('delete_collection', ['idCollection' => $collection['idCollection']]);?>"
                        class="deleteCollection-btn" type="button">
                    delete collection
                </button>
                <button data-idCollection="<?=$collection['idCollection'] ?>"
                        data-ajax="<?=buildUrl('edit_collection', ['idCollection' => $collection['idCollection']]);?>"
                        class="editCollection-btn" type="button">
                    edit collection
                </button>
                <a href="<?=buildUrl('view_collection', ['id' => $collection['idCollection']]);?>">
                    <button data-idCollection="<?=$collection['idCollection'] ?>" class="viewCollection-btn" type="button">
                        view collection
                    </button>
                </a>
            </td>
        </tr>
        <tr>
            <th>Movie</th>
            <th>summary</th>
            <th>poster</th>
            <th>releaseYear</th>
            <th>internetRating</th>
            <th>userRating</th>
            <th>userText</th>
            <th>isFavorite</th>
            <th>createdAt</th>
            <th>userId</th>
            <th>Action</th>
        </tr>
        <?php if (isset($movies)): ?>
        <?php foreach ($movies as $movie): ?>
            <?php include MOVIE_TEMPLATE?>
<!--        <tr class="--><?php //='movie.phtml'.$movie['idMovie'].'-'.'collection'.$collection['idCollection'] ?><!--">-->
<!--            <td>-->
<!--                <p id="--><?php //=$movie['idMovie'] ?><!--">--><?php //= $movie['title'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['summary'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['poster'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['releaseYear'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['internetRating'] ?><!--</p>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['userRating'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['userText'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['isFavorite'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['createdAt'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <p>--><?php //= $movie['userId'] ?><!--</p>-->
<!--            </td>-->
<!--            <td>-->
<!--                <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                        data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                        data-ajax="--><?php //=buildUrl('delete_movie_from_collection', ['idCollection' => $collection['idCollection'],'movieId' => $movie['movieId'] ]);?><!--"-->
<!--                        class="deleteMovieFromCollection-btn"-->
<!--                        type="button">-->
<!--                    remove from collection-->
<!--                </button>-->
<!--                <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                        data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                        data-ajax="--><?php //=buildUrl('edit_movie', ['movieId' => $movie['movieId']]);?><!--"-->
<!--                        class="editMovie-btn" type="button">-->
<!--                    edit movie-->
<!--                </button>-->
<!--                <a href="--><?php //=buildUrl('view_movie', ['id' => $movie['movieId']]);?><!--">-->
<!--                    <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                            data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                            class="viewMovie-btn" type="button">-->
<!--                        view movie-->
<!--                    </button>-->
<!--                </a>-->
<!--            </td>-->
<!--        </tr>-->
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td colspan="11">
                    <p>No movies in this collection</p>
                </td>
            </tr>
        <?php endif ?>
    </table>
</div>
