<div class="layout">

    <aside class="layout-aside">
        <h3 id="collection-<?=$collection['idCollection'] ?>"><?= $collection['title'] ?></h3>
        <p><?= $collection['userText'] ?></p>
        <?php if (count($movies)>0) : ?>
            <p> Contain <?= count($movies); ?> movies</p>
        <?php else: ?>
            <p>No movie in that list</p>
        <?php endif; ?>
        <p>Created at : <?= $collection['createdAt'] ?></p>
        <button
                class="addMovieForm-btn"
                data-ajax="<?=buildUrl('add_movie')?>"
                data-collection = "<?=$collection['idCollection']?>"
        >Add a movie into List
        </button>
    </aside>


    <main>
        <div class="addMovieOverlay">
            <div class="addMovieOverlay-Container">
                <button class="closeAddMovieOverlay">Close</button>
                <form data-ajax="<?=buildUrl('add_movie')?>" class="addMovieForm">
                    <div>
                        <label for="movieTitle">Title:</label>
                        <input type="text" id="movieTitle" name="movieTitle" value="The Matrix">
                    </div>
                    <div>
                        <label for="movieSummary">Summary:</label>
                        <textarea id="movieSummary" name="movieSummary">A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.</textarea>
                    </div>
                    <div>
                        <label for="movieGenre">Genre:</label>
                        <input type="text" id="movieGenre" name="movieGenre" value="Science Fiction, Action">
                    </div>
                    <div>
                        <label for="movieImg">Poster:</label>
                        <input type="file" id="movieImg" name="movieImg">
                    </div>
                    <div>
                        <label for="releaseYear">Release Year:</label>
                        <input type="text" id="releaseYear" name="releaseYear" value="1999">
                    </div>
                    <div>
                        <label for="userRating">User Rating:</label>
                        <input type="text" id="userRating" name="userRating" value="9">
                    </div>
                    <div>
                        <input type="hidden" id="idCollection" value="<?=$collection['idCollection']?>">
                        <input class="addMovie-btn" type="submit" value="Add Movie">
                    </div>
                </form>

            </div>
        </div>


        <div class="movieCardsContainer">

            <?php foreach($movies as $movie) :?>
<!--            <div class="--><?php //='movie'.$movie['idMovie'] ?><!--">-->
                <div class="movieCardsContainer-movieCard  <?='movie'.$movie['idMovie'] ?>">
                    <img class="movieCardsContainer-movieCard-moviePoster"
                         src="<?= MOVIE_POSTER_PATH. $movie['poster'] ?>"
                         alt="<?= $movie['title'] ?>" >
                    <div class="movieCardsContainer-movieCard-movieDetails">
                        <h2 id="<?="movie".$movie['idMovie'] ?>" ><?= $movie['title'] ?></h2>
                        <p><?= $movie['summary'] ?></p>
                        <div class="movieCardsContainer-movieCard-movieMeta">
                            <span>Released in <?= $movie['releaseYear'] ?></span>
                            <span>Internet rating: <?= $movie['internetRating'] ?></span>
                            <span>User rating: <?= $movie['userRating'] ?></span>
                        </div>
                        <div class="movieCardsContainer-movieCard-movieActions">
                            <button data-idMovie="<?=$movie['idMovie'] ?>"
                                    data-ajax="<?=buildUrl('delete_movie', ['idMovie' => $movie['idMovie'] ]);?>"
                                    class="deleteMovie-btn"
                                    type="button">
                                delete
                            </button>
                            <button data-idMovie="<?=$movie['idMovie'] ?>"
                                    data-ajax="<?=buildUrl('edit_movie', ['idMovie' => $movie['idMovie']]);?>"
                                    class="editMovie-btn" type="button">
                                edit movie
                            </button>
                            <a href="<?=buildUrl('view_movie', ['id' => $movie['idMovie']]);?>">
                                <button data-idMovie="<?=$movie['idMovie'] ?>"
                                        class="viewMovie-btn" type="button">
                                    view movie
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
<!--            </div>-->
            <?php endforeach ?>


        </div>
    </main>

</div>

