<fieldset>
    <form action="../controllers/add_list.php" method="post" >
        <label for="list">List</label><br>
        <input type="text" id="list" name="list"><br>
        <button type="submit">Add</button>
    </form>
</fieldset>

<fieldset>
    <form action="../controllers/add_movie.php" method="post" >
        <label for="movie">Movie:</label><br>
        <input type="text" id="movie" name="movie_title"><br>
        <select name="list">
            <?php foreach ($lists as $list) :?>
                <option value= "<?=htmlspecialchars($list['id_list']);?>" ><?=htmlspecialchars($list['name']);?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Add</button>
    </form>
</fieldset>




<div class="allList">
    <?php if (isset($lists)): ?>
        <?php foreach ($lists as $list): ?>

            <table class="<?='list-'.$list['id_list'] ?>">
                <tr>
                    <th colspan="3">
                        <h3 id="list-<?=$list['id_list'] ?>"><?= $list['name'] ?></h3>
                        <button data-idList="<?=$list['id_list'] ?>" class="deleteList-btn" type="button">
                            delete list
                        </button>
                        <button data-idList="<?=$list['id_list'] ?>" class="editList-btn" type="button">
                            edit list
                        </button>
                        <a href="<?=buildUrl('view_list', ['id' => $list['id_list']]);?>">
                            <button data-idList="<?=$list['id_list'] ?>" class="viewList-btn" type="button">
                                view list
                            </button>
                        </a>

                    </th>
                </tr>
                <tr>
                    <th>Movie</th>
                    <th>Action</th>
                </tr>
                <?php if (isset($list['movies']) && !empty($list['movies'])): ?>
                    <?php foreach ($list['movies'] as $movie): ?>
                        <tr class="<?='movie'.$movie['id_movie'].'-'.'list'.$list['id_list'] ?>">
                            <td>
                                <p id="<?="movie".$movie['id_movie'] ?>"><?= $movie['title'] ?></p>
                            </td>
                            <td>
                                <button data-idList="<?=$list['id_list'] ?>" data-idMovie="<?=$movie['id_movie'] ?>" class="deleteMovieFromList-btn" type="button">
                                    remove from list
                                </button>
                                <button data-idList="<?=$list['id_list'] ?>" data-idMovie="<?=$movie['id_movie'] ?>" class="updateMovie-btn" type="button">
                                    edit movie
                                </button>
                                <a href="<?=buildUrl('view_movie', ['id' => $movie['id_movie']]);?>">
                                    <button data-idList="<?=$list['id_list'] ?>" data-idMovie="<?=$movie['id_movie'] ?>" class="viewMovie-btn" type="button">
                                        view movie
                                    </button>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                <?php else: ?>
                    <tr>
                        <td colspan="3">
                            <p>No movies in this list</p>
                        </td>
                    </tr>
                <?php endif ?>
            </table>
        <?php endforeach ?>
    <?php endif; ?>
</div>












<!--<ul>-->
<!--    --><?php //foreach ($lists as $list): ?>
<!--        <li>--><?php //= htmlspecialchars($list['name']) ?><!--</li>-->
<!--    --><?php //endforeach; ?>
<!--</ul>-->


<!--<div class="allList">-->
<!---->
<!--        --><?php //foreach ($lists as $list): ?>
<!--           --><?php ////echo dump($list) ?>
<!--            <table class="--><?php //='list-'.$list['id_list'] ?><!--">-->
<!--                <tr>-->
<!--                    <th colspan="3">-->
<!--                        <h3 id="list---><?php //=$list['id_list'] ?><!--">--><?php //= $list['name'] ?><!--</h3>-->
<!--                        <button data-idList="--><?php //=$list['id_list'] ?><!--" class="deleteList-btn" type="button">-->
<!--                            delete list-->
<!--                        </button>-->
<!--                        <button data-idList="--><?php //=$list['id_list'] ?><!--" class="editList-btn" type="button">-->
<!--                            edit list-->
<!--                        </button>-->
<!--                        <button data-idList="--><?php //=$list['id_list'] ?><!--" class="viewList-btn" type="button">-->
<!--                            view list-->
<!--                        </button>-->
<!--                    </th>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <th>Movie</th>-->
<!--                    <th>Action</th>-->
<!--                </tr>-->
<!--                    --><?php //foreach ($list['movies'] as $movie): ?>
<!--                        <tr class="--><?php //='movie'.$movie['id_movie'].'-'.'list'.$list['id_list'] ?><!--">-->
<!--                            <td>-->
<!--                                <p id="--><?php //="movie".$movie['id_movie'] ?><!--">--><?php //= $movie['title'] ?><!--</p>-->
<!--                            </td>-->
<!--                            <td>-->
<!--                                <button data-idList="--><?php //=$list['id_list'] ?><!--" data-idMovie="--><?php //=$movie['id_movie'] ?><!--" class="deleteMovie-btn" type="button">-->
<!--                                    delete from list-->
<!--                                </button>-->
<!--                                <button data-idList="--><?php //=$list['id_list'] ?><!--" data-idMovie="--><?php //=$movie['id_movie'] ?><!--" class="updateMovie-btn" type="button">-->
<!--                                    edit movie-->
<!--                                </button>-->
<!--                                <button data-idList="--><?php //=$list['id_list'] ?><!--" data-idMovie="--><?php //=$movie['id_movie'] ?><!--" class="viewMovie-btn" type="button">-->
<!--                                    view movie-->
<!--                                </button>-->
<!--                            </td>-->
<!--                        </tr>-->
<!--                    --><?php //endforeach ?>
<!--            </table>-->
<!--        --><?php //endforeach ?>
<!---->
<!--</div>-->



<!--TODO: display errors-->