<div class="allList">
    <?php foreach ($lists as $list): ?>
<!--    --><?php //echo '<pre>';
//        print_r($lists);
//        echo '</pre>';?>
        <div>
            <h3><?= $list['name'] ?></h3>
            <?php if (isset($list['movies']) && !empty($list['movies'])): ?>
                <?php foreach ($list['movies'] as $movie): ?>
                    <p><?= $movie['title'] ?></p>
                <?php endforeach ?>
            <?php else: ?>
                <p>No movies in this list</p>
            <?php endif ?>
        </div>
    <?php endforeach ?>

</div>
