<div class="allList">
    <?php if (isset($lists)): ?>
        <?php foreach ($lists as $list): ?>
            <div class="<?='list-'.$list['id_list'] ?>">
            <div>
                <h3><?= $list['name'] ?></h3>
                <button data-idList="<?=$list['id_list'] ?>" class="deleteList-btn" type="button">
                    delete list
                </button>
            </div>
                <?php if (isset($list['movies']) && !empty($list['movies'])): ?>
                    <?php foreach ($list['movies'] as $movie): ?>
                        <div class="<?='movie'.$movie['id_movie'].'-'.'list'.$list['id_list'] ?>">
                            <p><?= $movie['title'] ?></p>
                            <button data-idList="<?=$list['id_list'] ?>" data-idMovie="<?=$movie['id_movie'] ?>" class="deleteMovie-btn" type="button">
                                delete movie
                            </button>
                        </div>
                    <?php endforeach ?>
                <?php else: ?>
                    <p>No movies in this list</p>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php endif; ?>

</div>
