<div class="loginContainer">
    <form action="<?php buildUrl('home') ?>" method="POST" class="loginContainer-formLogin">
        <?php if (isset($error)): ?>
            <p class="loginContainer-formLogin-error"><?= htmlspecialchars($error); ?></p>
        <?php endif; ?>
        <div>
            <label for="email" class="loginContainer-formLogin-label">Email</label>
            <input type="text" id="email" name="email" value="<?= htmlspecialchars($email ?? ""); ?>" class="loginContainer-formLogin-input">
        </div>
        <div>
            <label for="password" class="loginContainer-formLogin-label">Password</label>
            <input type="password" id="password" name="password" class="loginContainer-formLogin-input">
        </div>
        <input type="submit" value="Login" class="loginContainer-formLogin-submit">
        <div class="loginContainer-formLogin-forgotPassword">
            <a href="<?=buildUrl('password_reset');?>">Forgot password?</a>
        </div>
        <div class="loginContainer-formLogin-register">
            <p>Not yet registered?</p>
            <a href="<?=buildUrl('signup');?>">Register now</a>
        </div>
    </form>
</div>
