<!--<tr class="--><?php //='movie.phtml'.$movie['idMovie'].'-'.'collection'.$collection['idCollection'] ?><!--">-->
<!--    <td>-->
<!--        <p id="--><?php //=$movie['idMovie'] ?><!--">--><?php //= $movie['title'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['summary'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['poster'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['releaseYear'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['internetRating'] ?><!--</p>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['userRating'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['userText'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['isFavorite'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['createdAt'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <p>--><?php //= $movie['userId'] ?><!--</p>-->
<!--    </td>-->
<!--    <td>-->
<!--        <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                data-ajax="--><?php //=buildUrl('delete_movie_from_collection', ['idCollection' => $collection['idCollection'],'movieId' => $movie['movieId'] ]);?><!--"-->
<!--                class="deleteMovieFromCollection-btn"-->
<!--                type="button">-->
<!--            remove from collection-->
<!--        </button>-->
<!--        <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                data-ajax="--><?php //=buildUrl('edit_movie', ['movieId' => $movie['movieId']]);?><!--"-->
<!--                class="editMovie-btn" type="button">-->
<!--            edit movie-->
<!--        </button>-->
<!--        <a href="--><?php //=buildUrl('view_movie', ['id' => $movie['movieId']]);?><!--">-->
<!--            <button data-idCollection="--><?php //=$collection['idCollection'] ?><!--"-->
<!--                    data-idMovie="--><?php //=$movie['movieId'] ?><!--"-->
<!--                    class="viewMovie-btn" type="button">-->
<!--                view movie-->
<!--            </button>-->
<!--        </a>-->
<!--    </td>-->
<!--</tr>-->


<!--<table>-->
    <tr class="<?='movie'.$movie['idMovie'] ?>">
        <td>
            <p id="<?="movie".$movie['idMovie'] ?>"><?= $movie['title'] ?></p>
        </td>
        <td>
            <p><?= $movie['summary'] ?></p>
        </td>
        <td>
            <p><?= $movie['poster'] ?></p>
        </td>
        <td>
            <p><?= $movie['releaseYear'] ?></p>
        </td>
        <td>
            <p><?= $movie['internetRating'] ?></p>
        </td>
        <td>
            <p><?= $movie['userRating'] ?></p>
        </td>
        <td>
            <p><?= $movie['userText'] ?></p>
        </td>
        <td>
            <p><?= $movie['isFavorite'] ?></p>
        </td>
        <td>
            <p><?= $movie['createdAt'] ?></p>
        </td>
        <td>
            <p><?= $movie['userId'] ?></p>
        </td>
        <td>
            <button data-idMovie="<?=$movie['idMovie'] ?>"
                    data-ajax="<?=buildUrl('delete_movie', ['idMovie' => $movie['idMovie'] ]);?>"
                    class="deleteMovie-btn"
                    type="button">
                delete
            </button>
            <button data-idMovie="<?=$movie['idMovie'] ?>"
                    data-ajax="<?=buildUrl('edit_movie', ['idMovie' => $movie['idMovie']]);?>"
                    class="editMovie-btn" type="button">
                edit movie
            </button>
            <a href="<?=buildUrl('view_movie', ['id' => $movie['idMovie']]);?>">
                <button data-idMovie="<?=$movie['idMovie'] ?>"
                        class="viewMovie-btn" type="button">
                    view movie
                </button>
            </a>
        </td>
    </tr>
<!--</table>-->

<!--<div class="--><?php //='movie'.$movie['idMovie'] ?><!--">-->
<!--    <div class="movie-card">-->
<!--        <img src="--><?php //= MOVIE_POSTER_PATH. $movie['poster'] ?><!--" alt="--><?php //= $movie['title'] ?><!--" >-->
<!--        <div class="movie-details">-->
<!--            <h2 id="--><?php //="movie".$movie['idMovie'] ?><!--" >--><?php //= $movie['title'] ?><!--</h2>-->
<!--            <p>--><?php //= $movie['summary'] ?><!--</p>-->
<!--            <div class="movie-meta">-->
<!--                <span>Released in --><?php //= $movie['releaseYear'] ?><!--</span>-->
<!--                <span>Internet rating: --><?php //= $movie['internetRating'] ?><!--</span>-->
<!--                <span>User rating: --><?php //= $movie['userRating'] ?><!--</span>-->
<!--                <span>User text: --><?php //= $movie['userText'] ?><!--</span>-->
<!--                <span>isFavorite: --><?php //= $movie['isFavorite'] ?><!--</span>-->
<!--                <span>Created at: --><?php //= $movie['createdAt'] ?><!--</span>-->
<!--                <span>user id: --><?php //= $movie['userId'] ?><!--</span>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="movie-actions">-->
<!--            <button data-idMovie="--><?php //=$movie['idMovie'] ?><!--"-->
<!--                    data-ajax="--><?php //=buildUrl('delete_movie', ['idMovie' => $movie['idMovie'] ]);?><!--"-->
<!--                    class="deleteMovie-btn"-->
<!--                    type="button">-->
<!--                delete-->
<!--            </button>-->
<!--            <button data-idMovie="--><?php //=$movie['idMovie'] ?><!--"-->
<!--                    data-ajax="--><?php //=buildUrl('edit_movie', ['idMovie' => $movie['idMovie']]);?><!--"-->
<!--                    class="editMovie-btn" type="button">-->
<!--                edit movie-->
<!--            </button>-->
<!--            <a href="--><?php //=buildUrl('view_movie', ['id' => $movie['idMovie']]);?><!--">-->
<!--                <button data-idMovie="--><?php //=$movie['idMovie'] ?><!--"-->
<!--                        class="viewMovie-btn" type="button">-->
<!--                    view movie-->
<!--                </button>-->
<!--            </a>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
