<table>
    <tr class="<?='movie'.$movie['id_movie'] ?>">
        <td>
            <p id="<?="movie".$movie['id_movie'] ?>"><?= $movie['title'] ?></p>
        </td>
        <td>
            <button data-idMovie="<?=$movie['id_movie'] ?>"
                    data-ajax="<?=buildUrl('delete_movie', ['id_movie' => $movie['id_movie'] ]);?>"
                    class="deleteMovie-btn"
                    type="button">
                delete
            </button>
            <button data-idMovie="<?=$movie['id_movie'] ?>"
                    data-ajax="<?=buildUrl('edit_movie', ['id_movie' => $movie['id_movie']]);?>"
                    class="editMovie-btn" type="button">
                edit movie
            </button>
            <a href="<?=buildUrl('view_movie', ['id' => $movie['id_movie']]);?>">
                <button data-idMovie="<?=$movie['id_movie'] ?>"
                        class="viewMovie-btn" type="button">
                    view movie
                </button>
            </a>
        </td>
    </tr>


</table>

