
<main class="layout2">
    <form class="movieSearchForm" action="" method="post">
        <label for="searchInput" > Search : </label>
        <input name="searchInput" id="searchInput" class="apiSearchInput" type="text">
        <input class="submitBtn" type="submit" value="Search">
    </form>


    <div class="resultContainer">
        <div class="resultContainer-movieCard">
            <div class="resultContainer-movieCard-poster">
                <img src="https://image.tmdb.org/t/p/w300//gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg">
            </div>
            <div class="resultContainer-movieCard-movieDetails">
                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man</h3>
                <p class="resultContainer-movieCard-movieDetails-overview">
                    After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.
                </p>
                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2002-05-01</p>
                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.3</p>
                <button data-movieid ='557' class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>
            </div>
        </div>




<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//c24sv2weTHPsmDa7jEMN0m2P3RT.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: Homecoming</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2017-07-05</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.4</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: No Way Home</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2021-12-15</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 8</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//rmGLCH63IBByBx5SCbsn0pNWHdg.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man 3</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2007-05-01</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.4</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//xEBwdpXXS24WNqs3lMLU4bsee9i.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: Convergence</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Down on his luck Peter Parker, who after coming into contact with a device capable of inter-dimensional travel, meets another Spider-Man (Miles Morales) from a parallel earth. Miles and Peter are forced to work together to stop the forces that aim to harm them while Peter attempts to make his way home before it's too late.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2023-12-31</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 0</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">The Amazing Spider-Man</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2012-06-23</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.7</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//jNxRHZ2cxVkNRtxgHuCtv7GY4JP.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">When an extortionist threatens to force a multi-suicide unless a huge ransom is paid, only Peter Parker can stop him with his new powers as Spider-Man.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1978-03-15</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 5.8</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//olxpyq9kJAZ2NU1siLshhhXEPR7.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man 2</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can't act on his feelings for Mary Jane Watson, a girl he's loved since childhood. A certain anger begins to brew in his best friend Harry Osborn as well...</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2004-06-25</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.2</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//4q2NNj4S5dG2RLF9CpXsej7yXl.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: Far from Home</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2019-06-28</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.5</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">The Amazing Spider-Man 2</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2014-04-16</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.5</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//iiZZdoQBEYBv6id8su7ImL0oCbD.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: Into the Spider-Verse</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2018-12-14</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 8.4</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//6KcTa6doU5eJRfAMiwzUasHvqdu.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Italian Spiderman</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">This is an Australian-made parody of Italian action–adventure films of the 60s and 70s. and foreign movies that misappropriated popular American superheroes such as the Japanese TV series “Spider-Man”. (It should be noted that the Japanese Spider-Man was officially sanctioned by Marvel and is considered canon in the Marvel universe) This is an Italian take on the comic book superhero Spider-Man.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2007-11-08</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.4</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//zknrogDlwcmaz3yHkA3yEhy005t.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: Across the Spider-Verse</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">After reuniting with Gwen Stacy, Miles Morales — Brooklyn's full-time, friendly neighborhood Spider-Man — is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must redefine what it means to be a hero so he can save the people he loves most.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2023-06-02</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 0</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//ylLqcbXOdkZnJxHc09bybCtUTEb.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spiderman, Save Me</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">we all just wanna be famous on the internet.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: </p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 9.9</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//fb5R5DUOT4NfhZn8903c1gYGHJz.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man Strikes Back</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">At the New York State University, one of Peter Parker's tutors has accidentally given three students all the materials they need to create an atomic bomb. While Peter Parker tries to find out what's happened, the police suspect him of the crime, and Peter has to deal with an attractive journalist determined to get an interview with Spider-Man. Then dastardly millionaire Mr. White shows up, and will stop at nothing to get his hands on the atomic bomb. Spider-Man must defeat this scheming villain and stop him blowing up the World Trade Centre.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1978-12-21</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 5.5</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//ilmsQLtthtcD8EU1k25cp0xFQ9a.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: The Venom Saga</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">A space-shuttle crash-landing puts the famous web-slinger Spider-Man in contact with a living alien substance that bonds to his suit and enhances his super-powers. Unfortunately, the alien substance begins to change him and he feels the pull of evil, so discards the suit. The evil attaches itself to another host leading to an epic confrontation between good and evil.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1994-06-07</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.7</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//iYBfBk1i9zjN9Vybbj8UgTYzkyv.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Spider-man must rescue the beautiful daughter of the evil Dr. Lightning.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1969-01-01</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.8</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//mEtyZBbVl0sx0y1blYuVDgeNLkr.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Daredevil vs. Spider-Man</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Spider-Man and Daredevil team up to fight Kingpin.</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1994-11-19</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7.4</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="../public/img/movie_posters/missing.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview"></p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 1990-01-01</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 6.8</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="resultContainer-movieCard">-->
<!--            <img src="https://image.tmdb.org/t/p/w300//e2LLmI5wKIrWGAy9Of3yyWu7Szn.jpg" class="resultContainer-movieCard-poster">-->
<!--            <div class="resultContainer-movieCard-movieDetails">-->
<!--                <h3 class="resultContainer-movieCard-movieDetails-title">Spider-Man: All Roads Lead to No Way Home</h3>-->
<!--                <p class="resultContainer-movieCard-movieDetails-overview">Join our hosts JB Smoove and Martin Starr for a celebration of 20 years of Spider-Man™ movies!  From the original Sam Raimi trilogy to Marc Webb’s “amazing” movies to the latest trio from Director Jon Watts, we will take viewers through the stars, the stunts and action, the villains and heroes and an homage to Stan Lee, along with a few surprises. Find your favourite Spider-Man pajamas and prepare to swing through the past two decades of Spider-Man at the movies!</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-releaseDate">Release date: 2022-05-03</p>-->
<!--                <p class="resultContainer-movieCard-movieDetails-voteAverage">Vote average: 7</p>-->
<!--                <button class="resultContainer-movieCard-movieDetails-addBtn">add to a collection</button>-->
<!--            </div>-->
<!--        </div>-->
    </div>
    <div class="overlay" id="overlay">
        <div class="overlay-content">
            <img class="movie-img" src="" alt="">
            <div class="movie-info">
                <h2 id="movie-title"></h2>
                <p id="movie-description"></p>
                <p id="movie-rating"></p>
                <p id="movie-genre"></p>
                <button id="close-overlay">Close</button>
                <button id="add to collection">Close</button>
            </div>
        </div>
    </div>



</main>




