<form action="<?=buildUrl('signup');?>" method="POST">
    <div>
        <label for="username">Username</label>
        <input type="text" id="username" name="username" value="<?=htmlspecialchars($username);?>">
        <?php if (isset($errors['username'])): ?>
            <p class="error"><?=htmlspecialchars($errors['username']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="email">Email</label>
        <input type="text" id="email" name="email" value="<?=htmlspecialchars($email);?>">
        <?php if (isset($errors['email'])): ?>
            <p class="error"><?=htmlspecialchars($errors['email']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="password">
        <?php if (isset($errors['password'])): ?>
            <p class="error"><?=htmlspecialchars($errors['password']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="password-confirm">Password (confirmation)</label>
        <input type="password" id="password-confirm" name="password-confirm">
        <?php if (isset($errors['password-confirm'])): ?>
            <p class="error"><?=htmlspecialchars($errors['password-confirm']);?></p>
        <?php endif; ?>
    </div>
    <input type="submit" value="Sign up">
</form>

