<form action="<?=buildUrl('signin');?>" method="POST">
    <div>
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" name="firstname" value="<?=htmlspecialchars($firstname);?>">
        <?php if (isset($errors['firstname'])): ?>
            <p class="error"><?=htmlspecialchars($errors['firstname']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" name="lastname" value="<?=htmlspecialchars($firstname);?>">
        <?php if (isset($errors['lastname'])): ?>
            <p class="error"><?=htmlspecialchars($errors['lastname']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="email">Email</label>
        <input type="text" id="email" name="email" value="<?=htmlspecialchars($email);?>">
        <?php if (isset($errors['email'])): ?>
            <p class="error"><?=htmlspecialchars($errors['email']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password">
        <?php if (isset($errors['password'])): ?>
            <p class="error"><?=htmlspecialchars($errors['password']);?></p>
        <?php endif; ?>
    </div>
    <div>
        <label for="password-confirm">Mot de passe (confirmation)</label>
        <input type="password" id="password-confirm" name="password-confirm">
        <?php if (isset($errors['password-confirm'])): ?>
            <p class="error"><?=htmlspecialchars($errors['password-confirm']);?></p>
        <?php endif; ?>
    </div>
    <input type="submit" value="Enregistrer">
</form>