<div class="signupContainer">
    <form action="<?= buildUrl('signup');?>" method="POST" class="signupContainer-formSignup">
        <div>
            <label for="username" class="signupContainer-formSignup-label">Username</label>
            <input type="text" id="username" name="username" value="<?= htmlspecialchars($username);?>" class="signupContainer-formSignup-input">
            <?php if (isset($errors['username'])): ?>
                <p class="signupContainer-formSignup-error"><?= htmlspecialchars($errors['username']);?></p>
            <?php endif; ?>
        </div>
        <div>
            <label for="email" class="signupContainer-formSignup-label">Email</label>
            <input type="text" id="email" name="email" value="<?= htmlspecialchars($email);?>" class="signupContainer-formSignup-input">
            <?php if (isset($errors['email'])): ?>
                <p class="signupContainer-formSignup-error"><?= htmlspecialchars($errors['email']);?></p>
            <?php endif; ?>
        </div>
        <div>
            <label for="password" class="signupContainer-formSignup-label">Password</label>
            <input type="password" id="password" name="password" class="signupContainer-formSignup-input">
            <?php if (isset($errors['password'])): ?>
                <p class="signupContainer-formSignup-error"><?= htmlspecialchars($errors['password']);?></p>
            <?php endif; ?>
        </div>
        <div>
            <label for="password-confirm" class="signupContainer-formSignup-label">Password (confirmation)</label>
            <input type="password" id="password-confirm" name="password-confirm" class="signupContainer-formSignup-input">
            <?php if (isset($errors['password-confirm'])): ?>
                <p class="signupContainer-formSignup-error"><?= htmlspecialchars($errors['password-confirm']);?></p>
            <?php endif; ?>
        </div>
        <input type="submit" value="Sign up" class="signupContainer-formSignup-submit">
    </form>
</div>

