<div class="user-info">
    <table>
        <tr>
            <th>Pseudonym</th>
            <th>Email</th>
            <th>Role</th>
            <th>Created At</th>
        </tr>
        <tr>
            <td>
                <p><?= $user['username'] ?></p>
            </td>
            <td>
                <p><?= $user['email'] ?></p>
            </td>
            <td>
                <p><?= $user['role'] ?></p>
            </td>
            <td>
                <p><?= $user['createdAt'] ?></p>
            </td>
        </tr>
    </table>
    <a href="<?= buildUrl('delete_user', ['id' => $user['idUser']]) ?>" onclick="return confirm('Are you sure you want to delete this user?');">Delete User</a>
</div>
