<table>
    <tr>
        <th colspan="2" >user</th>
        <th>action</th>

    </tr>
    <tr>
        <th>Name</th>
        <td><?= $user['firstname']  ?></td>
        <td>
            <button>Edit firstname</button>
        </td>
    </tr>
    <tr>
        <th>surname</th>
        <td><?= $user['lastname']  ?></td>
        <td>
            <button>Edit last name</button>
        </td>
    </tr>
    <tr>
        <th>mail</th>
        <td><?= $user['email']  ?></td>
        <td>
            <button>Edit mail</button>
        </td>
    </tr>
<!--    <tr>-->
<!--        <th>password</th>-->
<!--        <td>--><?php //= $user['password']  ?><!--</td>-->
<!--        <td>-->
<!--            <button>Edit name</button>-->
<!--        </td>-->
<!--    </tr>-->
</table>